#!/usr/bin/env bash
# Seed PalWorldSettings.ini from compose/.env on first run only.
# Does not overwrite an existing settings file (world/config already present).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
SETTINGS_DIR="${ROOT}/Saved/Config/LinuxServer"
SETTINGS_FILE="${SETTINGS_DIR}/PalWorldSettings.ini"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "missing ${ENV_FILE} — copy .env.example first:" >&2
  echo "  cp ${ROOT}/.env.example ${ENV_FILE}" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
# shellcheck source=/dev/null
source "${ENV_FILE}"
set +a

if [[ -f "${SETTINGS_FILE}" ]]; then
  echo "settings already present: ${SETTINGS_FILE} (skip seed)"
  exit 0
fi

escape_ini() {
  # Escape double-quotes for OptionSettings="..." values
  printf '%s' "${1:-}" | sed 's/"/\\"/g'
}

SERVER_NAME="${SERVER_NAME:-Palworld Local}"
SERVER_DESCRIPTION="${SERVER_DESCRIPTION:-Local PC compose}"
MAX_PLAYERS="${MAX_PLAYERS:-4}"
SERVER_PASSWORD="${SERVER_PASSWORD:-change-me-join}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-change-me-admin}"
RCON_ENABLED="${RCON_ENABLED:-True}"
REST_API_ENABLED="${REST_API_ENABLED:-True}"
CROSSPLAY_PLATFORMS="${CROSSPLAY_PLATFORMS:-(Steam,Xbox,PS5,Mac)}"
GAME_PORT_INI="${GAME_PORT:-8211}"
RCON_PORT_INI="${RCON_PORT:-25575}"
REST_PORT_INI="${REST_PORT:-8212}"

mkdir -p "${SETTINGS_DIR}"

cat >"${SETTINGS_FILE}" <<EOF
; Generated by compose/scripts/seed-settings.sh — edit freely after first start.
; Re-seed only by deleting this file (make compose-down first).
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(ServerName="$(escape_ini "${SERVER_NAME}")",ServerDescription="$(escape_ini "${SERVER_DESCRIPTION}")",ServerPlayerMaxNum=${MAX_PLAYERS},AdminPassword="$(escape_ini "${ADMIN_PASSWORD}")",ServerPassword="$(escape_ini "${SERVER_PASSWORD}")",PublicPort=${GAME_PORT_INI},RCONEnabled=${RCON_ENABLED},RCONPort=${RCON_PORT_INI},RESTAPIEnabled=${REST_API_ENABLED},RESTAPIPort=${REST_PORT_INI},CrossplayPlatforms="$(escape_ini "${CROSSPLAY_PLATFORMS}")")
EOF

echo "seeded ${SETTINGS_FILE}"
echo "  join password:  (SERVER_PASSWORD from .env)"
echo "  admin password: (ADMIN_PASSWORD from .env — keep private)"
